// The carry-propagate adder families of chiALU as parametric SystemVerilog.
// Every module has the one interface
//   #(parameter int W) (input [W-1:0] a, b, input cin, output [W-1:0] s, output cout)
// and computes s = a + b + cin exactly (cout the carry out of bit W-1), so the
// lane module of a seed can put any of them behind its add/sub/neg/abs/saturate
// ops. The family names are chialu/spaces/adder_spaces.py's; the parameters
// are the pins of a family's design choices the registry (families/__init__.py)
// maps. The blocked families (carry_skip, carry_select, carry_increment,
// sparse_prefix_hybrid), the end-around-carry, the truncated and the
// FPGA-chain families are generated by families/adder_ext.py around the
// library modules their slots name; the prefix families by families/prefix.py.

// ---------------------------------------------------------------- ripple_carry
// one full adder per bit, the carry rippling; CHUNK > 1 breaks the chain into
// chunks with an explicit carry wire between them (the chunk_width_bits choice).
// FORM is the full adder's logic: 0 generate_propagate (s = p ^ c, c' = g | p c),
// 1 two_half_adders_or (two half adders, the carries ORed), 2 xor_majority
// (s = a ^ b ^ c, c' = majority), 3 half_sum_mux_carry (c' = p ? c : a).
module fam_adder_ripple_carry #(parameter int W = 16, parameter int CHUNK = 1, parameter int FORM = 0)
  (input logic [W-1:0] a, input logic [W-1:0] b, input logic cin,
   output logic [W-1:0] s, output logic cout);
  localparam int BLOCKS = (W + CHUNK - 1) / CHUNK;
  logic [BLOCKS:0] block_carry;
  assign block_carry[0] = cin;
  for (genvar block_index = 0; block_index < BLOCKS; block_index = block_index + 1) begin : chunk
    localparam int LO = block_index * CHUNK;
    localparam int BW = LO + CHUNK > W ? W - LO : CHUNK;
    (* keep_hierarchy = "yes" *) fam_adder_ripple_chunk #(.W(BW), .FORM(FORM)) u_chunk(
      .a(a[LO +: BW]), .b(b[LO +: BW]), .cin(block_carry[block_index]),
      .s(s[LO +: BW]), .cout(block_carry[block_index+1]));
  end
  assign cout = block_carry[BLOCKS];
endmodule

module fam_adder_ripple_chunk #(parameter int W = 1, parameter int FORM = 0)
  (input logic [W-1:0] a, input logic [W-1:0] b, input logic cin,
   output logic [W-1:0] s, output logic cout);
  logic [W:0] c;
  assign c[0] = cin;
  genvar i;
  generate
    for (i = 0; i < W; i = i + 1) begin : fa
      if (FORM == 1) begin : two_ha
        wire s1 = a[i] ^ b[i];
        wire c1 = a[i] & b[i];
        wire c2 = s1 & c[i];
        assign s[i] = s1 ^ c[i];
        assign c[i+1] = c1 | c2;
      end else if (FORM == 2) begin : maj
        assign s[i] = a[i] ^ b[i] ^ c[i];
        assign c[i+1] = (a[i] & b[i]) | (a[i] & c[i]) | (b[i] & c[i]);
      end else if (FORM == 3) begin : muxc
        wire p = a[i] ^ b[i];
        assign s[i] = p ^ c[i];
        assign c[i+1] = p ? c[i] : a[i];
      end else begin : gp
        wire g = a[i] & b[i];
        wire p = a[i] ^ b[i];
        assign s[i] = p ^ c[i];
        assign c[i+1] = g | (p & c[i]);
      end
    end
  endgenerate
  assign cout = c[W];
endmodule

// -------------------------------------------------------- manchester_carry_chain
// the pass-device carry chain in its synthesizable form: per bit a kill, a
// propagate and a generate, the carry passing through the chain in segments of
// SEG bits (chain_segment_length). VARSKIP = 1 (variable_skip) bypasses a
// segment whose bits all propagate: the segment's carry-out is its carry-in.
module fam_adder_manchester_carry_chain #(parameter int W = 16, parameter int SEG = 4, parameter int VARSKIP = 0)
  (input logic [W-1:0] a, input logic [W-1:0] b, input logic cin,
   output logic [W-1:0] s, output logic cout);
  localparam int NS = (W + SEG - 1) / SEG;
  logic [W-1:0] g, p, k, pass;
  assign g = a & b;
  assign p = a ^ b;
  assign k = ~(a | b);
  assign pass = ~g & ~k;              // the carry passes when neither killed nor generated
  logic [NS:0] sc;                    // the carry into each segment
  assign sc[0] = cin;
  genvar j, i;
  generate
    for (j = 0; j < NS; j = j + 1) begin : seg
      localparam int LO = j * SEG;
      localparam int HI = (LO + SEG > W) ? W : LO + SEG;
      logic [HI-LO:0] c;
      assign c[0] = sc[j];
      for (i = 0; i < HI - LO; i = i + 1) begin : bit_
        assign c[i+1] = (pass[LO+i] & c[i]) | g[LO+i];
        assign s[LO+i] = p[LO+i] ^ c[i];
      end
      if (VARSKIP) begin : skip
        wire allpass = &pass[HI-1:LO];
        assign sc[j+1] = allpass ? sc[j] : c[HI-LO];
      end else begin : chain
        assign sc[j+1] = c[HI-LO];
      end
    end
  endgenerate
  assign cout = sc[NS];
endmodule

// ------------------------------------------------------------ the lookahead levels
// The carries into N elements from their generate and propagate pairs and a
// carry-in: LEVELS = 1 resolves the N elements flat, the element carries
// rippled (INTER = 0) or looked ahead (INTER = 1); LEVELS > 1 groups G
// elements into super-groups, resolves the super-group carries with the same
// structure one level up, and looks ahead inside every super-group.
module fam_adder_cla_level #(parameter int N = 4, parameter int G = 4, parameter int LEVELS = 1, parameter int INTER = 0)
  (input logic [N-1:0] gg, input logic [N-1:0] gp, input logic cin, output logic [N-1:0] c, output logic cout);
  genvar k, i;
  generate
    if (LEVELS <= 1 || N <= G) begin : flat
      if (INTER == 1) begin : lookahead
        for (k = 0; k < N; k = k + 1) begin : lg
          logic [k+1:0] t;
          assign t[0] = cin;
          for (i = 0; i <= k; i = i + 1) begin : tt
            assign t[i+1] = gg[i] | (gp[i] & t[i]);
          end
          assign c[k] = t[k];
          if (k == N - 1) begin : last
            assign cout = t[k+1];
          end
        end
      end else if (INTER == 2) begin : select
        logic [N:0] r;
        assign r[0] = cin;
        for (k = 0; k < N; k = k + 1) begin : rg
          assign r[k+1] = r[k] ? (gg[k] | gp[k]) : gg[k];
          assign c[k] = r[k];
        end
        assign cout = r[N];
      end else begin : ripple
        logic [N:0] r;
        assign r[0] = cin;
        for (k = 0; k < N; k = k + 1) begin : rg
          assign r[k+1] = gg[k] | (gp[k] & r[k]);
          assign c[k] = r[k];
        end
        assign cout = r[N];
      end
    end else begin : hier
      localparam int NS = (N + G - 1) / G;
      logic [NS-1:0] sgg, sgp, sc;
      for (k = 0; k < NS; k = k + 1) begin : sg
        localparam int LO = k * G;
        localparam int HI = (LO + G > N) ? N : LO + G;
        // the super-group's generate and propagate from its elements
        logic [HI-LO:0] lg, lp;
        assign lg[0] = 1'b0;
        assign lp[0] = 1'b1;
        for (i = 0; i < HI - LO; i = i + 1) begin : acc
          assign lg[i+1] = gg[LO+i] | (gp[LO+i] & lg[i]);
          assign lp[i+1] = gp[LO+i] & lp[i];
          // the lookahead carry into element LO+i from the super-group carry-in
          if (INTER == 2) begin : select
            assign c[LO+i] = sc[k] ? (lg[i] | lp[i]) : lg[i];
          end else begin : lookahead
            assign c[LO+i] = lg[i] | (lp[i] & sc[k]);
          end
        end
        assign sgg[k] = lg[HI-LO];
        assign sgp[k] = lp[HI-LO];
      end
      fam_adder_cla_level #(.N(NS), .G(G), .LEVELS(LEVELS - 1), .INTER(INTER))
        u_up (.gg(sgg), .gp(sgp), .cin(cin), .c(sc), .cout(cout));
    end
  endgenerate
endmodule

// -------------------------------------------------------------- carry_lookahead
// groups of G bits with a one-level lookahead inside the group (the carries of
// the group from its bit generates and propagates and the group carry-in); the
// group carries come from LEVELS levels of lookahead over the group generates
// and propagates (fam_adder_cla_level): rippled (INTER = 0), looked ahead
// (INTER = 1), or selected (INTER = 2: every group's sum is formed for both
// carry-ins and the rippled group carry selects it, the carry-select stage
// above lookahead blocks).
module fam_adder_carry_lookahead #(parameter int W = 16, parameter int G = 4, parameter int INTER = 0, parameter int LEVELS = 1)
  (input logic [W-1:0] a, input logic [W-1:0] b, input logic cin,
   output logic [W-1:0] s, output logic cout);
  localparam int NG = (W + G - 1) / G;
  logic [W-1:0] g, p;
  assign g = a & b;
  assign p = a ^ b;
  logic [NG-1:0] gc;                  // the carry into each group
  logic [NG-1:0] GG, GP;              // group generate and propagate
  genvar k, i;
  generate
    for (k = 0; k < NG; k = k + 1) begin : grp
      localparam int LO = k * G;
      localparam int HI = (LO + G > W) ? W : LO + G;
      localparam int NB = HI - LO;
      // the group's generate and propagate from its bits
      logic [NB:0] lg, lp;
      assign lg[0] = 1'b0;
      assign lp[0] = 1'b1;
      for (i = 0; i < NB; i = i + 1) begin : acc
        assign lg[i+1] = g[LO+i] | (p[LO+i] & lg[i]);
        assign lp[i+1] = p[LO+i] & lp[i];
      end
      assign GG[k] = lg[NB];
      assign GP[k] = lp[NB];
      if (INTER == 2) begin : select
        // both sums of the group, selected by the group carry
        logic [NB-1:0] c0, c1;
        for (i = 0; i < NB; i = i + 1) begin : cc
          assign c0[i] = lg[i];
          assign c1[i] = lg[i] | lp[i];
          assign s[LO+i] = p[LO+i] ^ (gc[k] ? c1[i] : c0[i]);
        end
      end else begin : direct
        for (i = 0; i < NB; i = i + 1) begin : cc
          assign s[LO+i] = p[LO+i] ^ (lg[i] | (lp[i] & gc[k]));
        end
      end
    end
    begin : levels
      fam_adder_cla_level #(.N(NG), .G(G), .LEVELS(LEVELS), .INTER(INTER))
        u_lvl (.gg(GG), .gp(GP), .cin(cin), .c(gc), .cout(cout));
    end
  endgenerate
endmodule

// ------------------------------------------------------------- conditional_sum
// base blocks of BASE bits ripple their sum and carry for both carry-ins; a
// level merges RADIX consecutive blocks (2 or 4: the selection radix) by
// selecting each upper block's pair by the carry out of the blocks below it
// within the merged group, until one block spans the word
module fam_adder_conditional_sum #(parameter int W = 16, parameter int BASE = 1, parameter int RADIX = 2)
  (input logic [W-1:0] a, input logic [W-1:0] b, input logic cin,
   output logic [W-1:0] s, output logic cout);
  localparam int R = (RADIX == 4) ? 4 : 2;
  localparam int BS = (BASE < 1) ? 1 : BASE;
  localparam int NB0 = (W + BS - 1) / BS;                 // the base blocks
  localparam int L = (NB0 <= 1) ? 0 : ((R == 4) ? ($clog2(NB0) + 1) / 2 : $clog2(NB0));
  localparam int NBP = 1;                                 // (unused: the padded count follows below)
  // the padded block count: R^L base blocks
  function automatic int powi(input int base_, input int e);
    int r_, i_;
    r_ = 1;
    for (i_ = 0; i_ < e; i_ = i_ + 1) r_ = r_ * base_;
    return r_;
  endfunction
  localparam int NBL = powi(R, L);                        // base blocks after padding
  localparam int WP = NBL * BS;                           // the padded width
  logic [WP-1:0] ap, bp;
  assign ap = {{(WP-W){1'b0}}, a};
  assign bp = {{(WP-W){1'b0}}, b};
  // per level: the sums under carry-in 0 and 1, and the carry out of the block a bit ends
  logic [WP-1:0] s0 [0:L];
  logic [WP-1:0] s1 [0:L];
  logic [WP-1:0] c0 [0:L];
  logic [WP-1:0] c1 [0:L];
  genvar l, i, m;
  generate
    // level 0: the base blocks rippled for both carry-ins
    for (i = 0; i < NBL; i = i + 1) begin : base
      localparam int LO = i * BS;
      logic [BS:0] r0, r1;
      assign r0[0] = 1'b0;
      assign r1[0] = 1'b1;
      for (m = 0; m < BS; m = m + 1) begin : bit_
        assign s0[0][LO+m] = ap[LO+m] ^ bp[LO+m] ^ r0[m];
        assign r0[m+1] = (ap[LO+m] & bp[LO+m]) | ((ap[LO+m] ^ bp[LO+m]) & r0[m]);
        assign s1[0][LO+m] = ap[LO+m] ^ bp[LO+m] ^ r1[m];
        assign r1[m+1] = (ap[LO+m] & bp[LO+m]) | ((ap[LO+m] ^ bp[LO+m]) & r1[m]);
        // the carry out of bit LO+m under the block's carry-in (the block's carry-out at its top bit)
        assign c0[0][LO+m] = r0[m+1];
        assign c1[0][LO+m] = r1[m+1];
      end
    end
    for (l = 0; l < L; l = l + 1) begin : lvl
      localparam int BW = BS * powi(R, l);                // the block width at this level
      for (i = 0; i < WP; i = i + 1) begin : bit_
        localparam int GRP = i / (BW * R);                // the merged group
        localparam int POS = (i / BW) % R;                // the block's position in the group
        localparam int GLO = GRP * BW * R;                // the group's first bit
        if (POS == 0) begin : lower
          assign s0[l+1][i] = s0[l][i];
          assign s1[l+1][i] = s1[l][i];
          assign c0[l+1][i] = c0[l][i];
          assign c1[l+1][i] = c1[l][i];
        end else begin : upper
          // the carry into this block under the group's carry-in 0 / 1: the chain of the blocks below
          logic [POS:0] k0, k1;
          assign k0[0] = 1'b0;
          assign k1[0] = 1'b1;
          genvar q;
          for (q = 0; q < POS; q = q + 1) begin : chain
            localparam int E = GLO + q * BW + BW - 1;     // the last bit of block q
            assign k0[q+1] = k0[q] ? c1[l][E] : c0[l][E];
            assign k1[q+1] = k1[q] ? c1[l][E] : c0[l][E];
          end
          assign s0[l+1][i] = k0[POS] ? s1[l][i] : s0[l][i];
          assign c0[l+1][i] = k0[POS] ? c1[l][i] : c0[l][i];
          assign s1[l+1][i] = k1[POS] ? s1[l][i] : s0[l][i];
          assign c1[l+1][i] = k1[POS] ? c1[l][i] : c0[l][i];
        end
      end
    end
  endgenerate
  assign s = cin ? s1[L][W-1:0] : s0[L][W-1:0];
  assign cout = cin ? c1[L][W-1] : c0[L][W-1];
endmodule

// ------------------------------------------------------------ prefix_and_incrementer
// s = a + cin: the carry into bit i is cin AND every lower bit, a prefix AND
// (STRUCTURE 0 a ripple AND chain, 1 a prefix AND tree of topology TOPO, 2
// select blocks of B bits whose block carry is the AND of the block)
module fam_incr_prefix_and #(parameter int W = 16, parameter int STRUCTURE = 1, parameter int B = 4, parameter int TOPO = 0)
  (input logic [W-1:0] a, input logic cin, output logic [W-1:0] s, output logic cout);
  // STRUCTURE: 0 ripple_and_chain, 1 prefix_and_tree (TOPO: 0 sklansky, 1 brent_kung, 2 kogge_stone),
  // 2 select_blocks of B bits
  logic [W:0] c;
  assign c[0] = cin;
  genvar i, l;
  generate
    if (STRUCTURE == 0) begin : ripple
      for (i = 0; i < W; i = i + 1) begin : ch
        assign c[i+1] = c[i] & a[i];
      end
    end else if (STRUCTURE == 1) begin : tree
      localparam int L = (W <= 1) ? 1 : $clog2(W);
      if (TOPO == 2) begin : kogge_stone
        // p[l][i]: AND of a[i] down to a[i - 2^l + 1]
        logic [W-1:0] p [0:L];
        for (i = 0; i < W; i = i + 1) begin : leaf
          assign p[0][i] = a[i];
        end
        for (l = 0; l < L; l = l + 1) begin : lvl
          for (i = 0; i < W; i = i + 1) begin : pos
            if (i >= (1 << l)) begin : comb
              assign p[l+1][i] = p[l][i] & p[l][i - (1 << l)];
            end else begin : keep
              assign p[l+1][i] = p[l][i];
            end
          end
        end
        for (i = 0; i < W; i = i + 1) begin : cy
          assign c[i+1] = cin & p[L][i];
        end
      end else if (TOPO == 1) begin : brent_kung
        // an up-sweep over the odd positions of each level, then a down-sweep filling the rest
        logic [W-1:0] p [0:2*L];
        for (i = 0; i < W; i = i + 1) begin : leaf
          assign p[0][i] = a[i];
        end
        for (l = 0; l < L; l = l + 1) begin : up
          for (i = 0; i < W; i = i + 1) begin : pos
            if (((i + 1) % (2 << l)) == 0) begin : comb
              assign p[l+1][i] = p[l][i] & p[l][i - (1 << l)];
            end else begin : keep
              assign p[l+1][i] = p[l][i];
            end
          end
        end
        for (l = 0; l < L; l = l + 1) begin : down
          localparam int D = 1 << (L - 1 - l);
          for (i = 0; i < W; i = i + 1) begin : pos
            if (((i + 1) % (2 * D)) == D && (i + 1) > D) begin : comb
              assign p[L+l+1][i] = p[L+l][i] & p[L+l][i - D];
            end else begin : keep
              assign p[L+l+1][i] = p[L+l][i];
            end
          end
        end
        for (i = 0; i < W; i = i + 1) begin : cy
          assign c[i+1] = cin & p[2*L][i];
        end
      end else begin : sklansky
        logic [W-1:0] p [0:L];           // p[l][i]: AND of a[i] down to a[i - 2^l + 1]
        for (i = 0; i < W; i = i + 1) begin : leaf
          assign p[0][i] = a[i];
        end
        for (l = 0; l < L; l = l + 1) begin : lvl
          for (i = 0; i < W; i = i + 1) begin : pos
            if ((i / (1 << l)) % 2 == 1) begin : comb   // the upper half of every block takes the lower half's end
              assign p[l+1][i] = p[l][i] & p[l][(i / (1 << l)) * (1 << l) - 1];
            end else begin : keep
              assign p[l+1][i] = p[l][i];
            end
          end
        end
        for (i = 0; i < W; i = i + 1) begin : cy
          assign c[i+1] = cin & p[L][i];
        end
      end
    end else begin : blocks
      localparam int NB = (W + B - 1) / B;
      logic [NB:0] bc;                  // the carry into each block
      assign bc[0] = cin;
      for (i = 0; i < NB; i = i + 1) begin : blk
        localparam int LO = i * B;
        localparam int HI = (LO + B - 1 < W - 1) ? LO + B - 1 : W - 1;
        logic all1;
        assign all1 = &a[HI:LO];
        assign bc[i+1] = bc[i] & all1;
        genvar j;
        for (j = LO; j <= HI; j = j + 1) begin : bit_
          if (j == LO) begin : first
            assign c[j+1] = bc[i] & a[j];
          end else begin : rest
            assign c[j+1] = c[j] & a[j];
          end
        end
      end
    end
  endgenerate
  assign s = a ^ c[W-1:0];
  assign cout = c[W];
endmodule
